name: Pull request semantic check
description: >-
  This action checks if the pull request title follows the conventional commits format.

inputs:
  types:
    type: string
    description: >-
      list of allowed commit types.
    required: false
    default: |
      feat
      fix
      docs
      style
      refactor
      perf
      test
      chore
      build
      ci
  requireScope:
    type: boolean
    description: >-
      Require scopes in PR titles.
    required: false
    default: true
  scopes:
    type: string
    description: >-
      list of allowed scopes. If empty, any scope is allowed.
    required: false
    default: ""
  subjectPattern:
    type: string
    description: >-
      regex pattern to match the subject of the PR title. If empty, any subject is allowed.
    required: false
    default: "^#[0-9]+.*$"
  no-comment:
    description: >-
      Don't post the PR title lint output as a comment on the PR. This is useful if
      you want to post the output somewhere else (e.g. a Slack channel)
      instead of as a PR comment.
    type: boolean
    required: false
    default: "false"
  exampleCommitTitle:
    type: string
    description: >-
      Example of a valid PR title.
    required: false
    default: "feat(ci): #1234 add new feature"

runs:
  using: composite
  steps:
    - name: Lint PR title
      id: lint-pr-title
      uses: amannn/action-semantic-pull-request@v6
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        types: ${{ inputs.types }}
        requireScope: ${{ inputs.requireScope }}
        scopes: ${{ inputs.scopes }}
        subjectPattern: ${{ inputs.subjectPattern }}
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}" didn't match the configured pattern. Please ensure that the subject matches the following pattern.

          Pattern: `${{ inputs.subjectPattern }}`
          Example: `${{ inputs.exampleCommitTitle }}`

    - name: PR Title Lint Error
      uses: marocchino/sticky-pull-request-comment@v3
      if: ${{ !cancelled() && steps.lint-pr-title.outputs.error_message != null && inputs.no-comment != 'true' }}
      with:
        header: pr-title-lint-error
        message: |
          Hey there and thank you for opening this pull request! :wave:

          We require pull request titles to follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) format. It looks like your proposed title needs to be adjusted.

          <details><summary>Details:</summary>
          
          ```
          ${{ steps.lint-pr-title.outputs.error_message }}
          ```

          </details>

    - name: Delete previous PR Title Lint Error
      uses: marocchino/sticky-pull-request-comment@v3
      if: ${{ !cancelled() && steps.lint-pr-title.outputs.error_message == null && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') }}
      with:
        header: pr-title-lint-error
        delete: true
