name: Conventional Commits

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: write
  statuses: write

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/semantic-pull-request
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            build
            ci
          requireScope: true
          scopes: |
            github
            ci
            devcontainer
            bootstrap
            terraform
            docs
          subjectPattern: "^#[0-9]+.*$"
          exampleCommitTitle: "feat(ci): #1234 add new feature"
